
services:

  app:
    build: .
    ports:
    - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    restart: unless-stopped

  db:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      start_interval: 1s
    env_file: .env
    restart: unless-stopped
