# Generated by Django 5.0.3 on 2024-04-08 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_tournament", models.BooleanField(default=False)),
                ("is_match_four", models.BooleanField(default=False)),
                ("has_started", models.BooleanField(default=False)),
                ("max_players", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12)),
                ("is_eliminated", models.BooleanField(default=False)),
                ("is_ai", models.BooleanField(default=False)),
                (
                    "lobby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.lobby"
                    ),
                ),
            ],
        ),
    ]
