# Generated by Django 5.0.3 on 2024-04-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_lobby_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="channel_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
