# Generated by Django 5.0.3 on 2024-05-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_channel_id_player_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_disconnected",
            field=models.BooleanField(default=False),
        ),
    ]
